# Generated by Django 5.2.5 on 2025-10-29 21:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cliente_segmentacion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SaldoCliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('saldo', models.DecimalField(decimal_places=8, default=0, help_text='Saldo disponible del cliente en esta moneda (soporta hasta 25 dígitos totales)', max_digits=25)),
                ('ultima_actualizacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Saldo de Cliente',
                'verbose_name_plural': 'Saldos de Clientes',
            },
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('cedula', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('ruc', models.CharField(blank=True, help_text='RUC del cliente en formato válido (ej: 8001234-6)', max_length=15, null=True, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('telefono', models.CharField(blank=True, max_length=20, null=True)),
                ('estado', models.CharField(default='activo', max_length=10)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('segmentacion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cliente_segmentacion.segmentacion')),
            ],
        ),
    ]
