# Generated by Django 5.2.5 on 2025-09-25 20:33

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cliente_usuario', '0003_initial'),
        ('clientes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='usuarios',
            field=models.ManyToManyField(related_name='clientes', through='cliente_usuario.Usuario_Cliente', to=settings.AUTH_USER_MODEL),
        ),
    ]
