# Generated by Django 5.2.5 on 2025-10-29 21:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cliente_usuario', '0003_initial'),
        ('clientes', '0001_initial'),
        ('monedas', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='usuarios',
            field=models.ManyToManyField(related_name='clientes', through='cliente_usuario.Usuario_Cliente', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='saldocliente',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saldos', to='clientes.cliente'),
        ),
        migrations.AddField(
            model_name='saldocliente',
            name='moneda',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='saldos_clientes', to='monedas.moneda'),
        ),
        migrations.AddIndex(
            model_name='saldocliente',
            index=models.Index(fields=['cliente', 'moneda'], name='clientes_sa_cliente_7c6d6b_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='saldocliente',
            unique_together={('cliente', 'moneda')},
        ),
    ]
