# Generated by Django 5.2.5 on 2025-08-27 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='cedula',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='segmentacion',
            name='estado',
            field=models.CharField(default='activo', help_text='Estado de la segmentación (activo/inactivo)', max_length=10),
        ),
    ]
