# Generated by Django 5.2.5 on 2025-10-22 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='ruc',
            field=models.CharField(blank=True, help_text='RUC del cliente en formato válido (ej: 8001234-6)', max_length=15, null=True, unique=True),
        ),
    ]
