# Generated by Django 5.2.5 on 2025-08-28 02:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0002_alter_cliente_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cliente',
            options={'default_permissions': (), 'permissions': [('agregar_cliente', 'Puede agregar cliente'), ('cambiar_cliente', 'Puede modificar cliente'), ('eliminar_cliente', 'Puede eliminar cliente'), ('ver_cliente', 'Puede ver cliente')]},
        ),
        migrations.AlterModelOptions(
            name='segmentacion',
            options={'default_permissions': (), 'permissions': [('agregar_segmentacion', 'Puede agregar segmentacion'), ('cambiar_segmentacion', 'Puede modificar segmentacion'), ('eliminar_segmentacion', 'Puede eliminar segmentacion'), ('ver_segmentacion', 'Puede ver segmentacion')]},
        ),
    ]
