# Generated by Django 5.2.5 on 2025-08-27 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0002_cliente_cedula_segmentacion_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='segmentacion',
            name='nombre',
            field=models.CharField(max_length=50),
        ),
    ]
