# Generated by Django 5.2.5 on 2025-10-29 23:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0002_initial'),
        ('monedas', '0001_initial'),
        ('tauser', '0001_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='saldocliente',
            name='clientes_sa_cliente_7c6d6b_idx',
        ),
        migrations.AlterUniqueTogether(
            name='saldocliente',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='saldocliente',
            name='localidad',
            field=models.ForeignKey(default=1, help_text='Localidad/sucursal donde está disponible este saldo', on_delete=django.db.models.deletion.PROTECT, related_name='saldos_clientes', to='tauser.localidad'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='saldocliente',
            unique_together={('cliente', 'moneda', 'localidad')},
        ),
        migrations.AddIndex(
            model_name='saldocliente',
            index=models.Index(fields=['cliente', 'moneda', 'localidad'], name='clientes_sa_cliente_ff4df6_idx'),
        ),
    ]
