# Generated by Django 5.2.5 on 2025-08-21 22:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0003_clienteusuario'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ClienteUsuario',
        ),
    ]
