# Generated by Django 5.2.5 on 2025-10-27 01:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0003_cliente_ruc'),
        ('monedas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SaldoCliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('saldo', models.DecimalField(decimal_places=8, default=0, help_text='Saldo disponible del cliente en esta moneda', max_digits=20)),
                ('ultima_actualizacion', models.DateTimeField(auto_now=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saldos', to='clientes.cliente')),
                ('moneda', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='saldos_clientes', to='monedas.moneda')),
            ],
            options={
                'verbose_name': 'Saldo de Cliente',
                'verbose_name_plural': 'Saldos de Clientes',
                'indexes': [models.Index(fields=['cliente', 'moneda'], name='clientes_sa_cliente_7c6d6b_idx')],
                'unique_together': {('cliente', 'moneda')},
            },
        ),
    ]
