# Generated by Django 5.2.5 on 2025-08-28 03:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0003_alter_cliente_options_alter_segmentacion_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cliente',
            options={},
        ),
        migrations.AlterModelOptions(
            name='segmentacion',
            options={},
        ),
    ]
