# Generated by Django 5.2.5 on 2025-10-27 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0004_saldocliente'),
    ]

    operations = [
        migrations.AlterField(
            model_name='saldocliente',
            name='saldo',
            field=models.DecimalField(decimal_places=8, default=0, help_text='Saldo disponible del cliente en esta moneda (soporta hasta 25 dígitos totales)', max_digits=25),
        ),
    ]
