# Generated by Django 5.2.5 on 2025-08-31 16:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0003_alter_segmentacion_nombre'),
        ('clientes', '0004_alter_cliente_options_alter_segmentacion_options'),
    ]

    operations = [
    ]
