# Generated by Django 5.2.5 on 2025-09-02 06:16

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cliente_usuario', '0002_usuario_cliente_delete_usuario_rol_cliente'),
        ('clientes', '0005_merge_20250831_1621'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='usuarios',
            field=models.ManyToManyField(related_name='clientes', through='cliente_usuario.Usuario_Cliente', to=settings.AUTH_USER_MODEL),
        ),
    ]
