# Generated by Django 5.2.5 on 2025-09-04 18:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cliente_segmentacion', '0001_initial'),
        ('clientes', '0006_cliente_usuarios'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='segmentacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cliente_segmentacion.segmentacion'),
        ),
        migrations.DeleteModel(
            name='Segmentacion',
        ),
    ]
