# Generated by Django 5.2.5 on 2025-09-04 21:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cliente_segmentacion', '0003_alter_segmentacion_descripcion_and_more'),
        ('cliente_usuario', '0002_usuario_cliente_delete_usuario_rol_cliente'),
        ('clientes', '0007_alter_cliente_segmentacion_delete_segmentacion'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='actualizado_en',
            field=models.DateTimeField(auto_now=True, help_text='Fecha y hora de última actualización del registro'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='cedula',
            field=models.CharField(blank=True, help_text='Número de cédula o identificación del cliente (opcional)', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='creado_en',
            field=models.DateTimeField(auto_now_add=True, help_text='Fecha y hora de creación del registro'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='email',
            field=models.EmailField(help_text='Correo electrónico único del cliente', max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='estado',
            field=models.CharField(default='activo', help_text='Estado del cliente (activo/inactivo)', max_length=10),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='nombre',
            field=models.CharField(help_text='Nombre completo del cliente', max_length=150),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='segmentacion',
            field=models.ForeignKey(help_text='Segmentación asignada al cliente; no se puede eliminar si está en uso', on_delete=django.db.models.deletion.PROTECT, to='cliente_segmentacion.segmentacion'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='telefono',
            field=models.CharField(blank=True, help_text='Número de teléfono del cliente (opcional)', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='usuarios',
            field=models.ManyToManyField(help_text='Usuarios asociados al cliente mediante tabla intermedia', related_name='clientes', through='cliente_usuario.Usuario_Cliente', to=settings.AUTH_USER_MODEL),
        ),
    ]
