# Generated by Django 5.2.5 on 2025-09-24 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0008_alter_cliente_actualizado_en_alter_cliente_cedula_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='cedula',
            field=models.CharField(blank=True, help_text='Número de cédula o identificación del cliente (opcional)', max_length=20, null=True, unique=True),
        ),
    ]
