# Generated by Django 5.2.5 on 2025-09-21 02:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cotizaciones', '0004_alter_tasadecambio_monto_compra_and_more'),
        ('monedas', '0002_moneda_estado'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaccion',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('monto', models.DecimalField(decimal_places=8, max_digits=23)),
                ('tipo', models.CharField(choices=[('compra', 'Compra'), ('venta', 'Venta')], max_length=10)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('confirmada', 'Confirmada'), ('cancelada_cotizacion', 'Cancelada por cambio de cotización'), ('cancelada_usuario', 'Cancelada por decisión del usuario')], default='pendiente', max_length=30)),
                ('tasa_usada', models.DecimalField(decimal_places=8, max_digits=23)),
                ('moneda_destino', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transacciones_destino', to='monedas.moneda')),
                ('moneda_origen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transacciones_origen', to='monedas.moneda')),
                ('tasa_ref', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cotizaciones.tasadecambio')),
            ],
        ),
    ]
