# Generated by Django 5.2.5 on 2025-10-29 21:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '0001_initial'),
        ('medio_acreditacion', '0001_initial'),
        ('metodos_pagos', '0001_initial'),
        ('monedas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaccion',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateTimeField(auto_now_add=True, help_text='Timestamp de creación (auto).')),
                ('monto', models.DecimalField(decimal_places=8, help_text='Monto base de la operación (interpretable según tipo).', max_digits=23)),
                ('tipo', models.CharField(choices=[('compra', 'Compra'), ('venta', 'Venta'), ('cambio', 'Cambio')], help_text='Compra o venta.', max_length=10)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('confirmada', 'Confirmada'), ('cancelada_cotizacion', 'Cancelada por cambio de cotización'), ('cancelada_usuario', 'Cancelada por decisión del usuario')], default='pendiente', help_text='Estado del ciclo de vida.', max_length=30)),
                ('ganancia', models.DecimalField(blank=True, decimal_places=8, help_text='Ganancia obtenida por la casa de cambio en esta transacción.', max_digits=23, null=True)),
                ('tasa_usada', models.DecimalField(decimal_places=8, help_text='Tasa concreta aplicada (con margen/comisión).', max_digits=23)),
                ('fecha_procesado', models.DateTimeField(blank=True, null=True)),
                ('monto_recibir', models.DecimalField(blank=True, decimal_places=8, help_text='Monto exacto que recibirá el cliente (ya con descuento aplicado)', max_digits=20, null=True)),
                ('cliente', models.ForeignKey(help_text='Cliente al que pertenece esta transacción.', on_delete=django.db.models.deletion.CASCADE, related_name='transacciones', to='clientes.cliente')),
                ('medio_acreditacion', models.ForeignKey(help_text='Medio de acreditacion utilizado para acreditar la transacción (ej: efectivo, transferencia).', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='medio_acreditacion', to='medio_acreditacion.medioacreditacion')),
                ('metodo_pago', models.ForeignKey(help_text='Método de pago utilizado en la transacción (ej: efectivo, transferencia).', on_delete=django.db.models.deletion.PROTECT, related_name='transacciones', to='metodos_pagos.metodopago')),
                ('moneda_destino', models.ForeignKey(help_text='Moneda que el usuario recibe.', on_delete=django.db.models.deletion.CASCADE, related_name='transacciones_destino', to='monedas.moneda')),
                ('moneda_origen', models.ForeignKey(help_text='Moneda que el usuario entrega.', on_delete=django.db.models.deletion.CASCADE, related_name='transacciones_origen', to='monedas.moneda')),
            ],
            options={
                'verbose_name': 'Transacción',
                'verbose_name_plural': 'Transacciones',
                'ordering': ['-fecha'],
            },
        ),
    ]
