# Generated by Django 5.2.5 on 2025-09-25 21:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('operaciones', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='transaccion',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transacciones', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='transaccion',
            index=models.Index(fields=['-fecha'], name='operaciones_fecha_eec922_idx'),
        ),
        migrations.AddIndex(
            model_name='transaccion',
            index=models.Index(fields=['estado'], name='operaciones_estado_6779ea_idx'),
        ),
    ]
