# Generated by Django 5.2.5 on 2025-10-01 04:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cotizaciones', '0001_initial'),
        ('monedas', '0001_initial'),
        ('operaciones', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='transaccion',
            options={'ordering': ['-fecha'], 'verbose_name': 'Transacción', 'verbose_name_plural': 'Transacciones'},
        ),
        migrations.AlterField(
            model_name='transaccion',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('confirmada', 'Confirmada'), ('cancelada_cotizacion', 'Cancelada por cambio de cotización'), ('cancelada_usuario', 'Cancelada por decisión del usuario')], default='pendiente', help_text='Estado del ciclo de vida.', max_length=30),
        ),
        migrations.AlterField(
            model_name='transaccion',
            name='fecha',
            field=models.DateTimeField(auto_now_add=True, help_text='Timestamp de creación (auto).'),
        ),
        migrations.AlterField(
            model_name='transaccion',
            name='moneda_destino',
            field=models.ForeignKey(help_text='Moneda que el usuario recibe.', on_delete=django.db.models.deletion.CASCADE, related_name='transacciones_destino', to='monedas.moneda'),
        ),
        migrations.AlterField(
            model_name='transaccion',
            name='moneda_origen',
            field=models.ForeignKey(help_text='Moneda que el usuario entrega.', on_delete=django.db.models.deletion.CASCADE, related_name='transacciones_origen', to='monedas.moneda'),
        ),
        migrations.AlterField(
            model_name='transaccion',
            name='monto',
            field=models.DecimalField(decimal_places=8, help_text='Monto base de la operación (interpretable según tipo).', max_digits=23),
        ),
        migrations.AlterField(
            model_name='transaccion',
            name='tasa_ref',
            field=models.ForeignKey(help_text='Referencia a la cotización base vigente al iniciar.', on_delete=django.db.models.deletion.PROTECT, to='cotizaciones.tasadecambio'),
        ),
        migrations.AlterField(
            model_name='transaccion',
            name='tasa_usada',
            field=models.DecimalField(decimal_places=8, help_text='Tasa concreta aplicada (con margen/comisión).', max_digits=23),
        ),
        migrations.AlterField(
            model_name='transaccion',
            name='tipo',
            field=models.CharField(choices=[('compra', 'Compra'), ('venta', 'Venta')], help_text='Compra o venta.', max_length=10),
        ),
        migrations.AlterField(
            model_name='transaccion',
            name='usuario',
            field=models.ForeignKey(blank=True, help_text='Usuario que originó la transacción (nullable para registros migrados).', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transacciones', to=settings.AUTH_USER_MODEL),
        ),
    ]
