# Generated by Django 5.2.5 on 2025-09-21 03:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('operaciones', '0002_transaccion_usuario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaccion',
            name='usuario',
        ),
    ]
