# Generated by Django 5.2.5 on 2025-10-01 13:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0002_initial'),
        ('operaciones', '0003_alter_transaccion_options_alter_transaccion_estado_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaccion',
            name='cliente',
            field=models.ForeignKey(default=1, help_text='Cliente al que pertenece esta transacción.', on_delete=django.db.models.deletion.CASCADE, related_name='transacciones', to='clientes.cliente'),
            preserve_default=False,
        ),
    ]
