# Generated by Django 5.2.5 on 2025-10-06 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operaciones', '0004_transaccion_cliente'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaccion',
            name='ganancia',
            field=models.DecimalField(blank=True, decimal_places=8, help_text='Ganancia obtenida por la casa de cambio en esta transacción.', max_digits=23, null=True),
        ),
    ]
