# Generated by Django 5.2.5 on 2025-09-25 10:42

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cotizaciones', '0005_tasadecambio_comision_compra_and_more'),
        ('monedas', '0002_moneda_estado'),
        ('operaciones', '0004_transaccion_usuario'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='transaccion',
            options={'ordering': ['-fecha']},
        ),
        migrations.AddIndex(
            model_name='transaccion',
            index=models.Index(fields=['-fecha'], name='operaciones_fecha_eec922_idx'),
        ),
        migrations.AddIndex(
            model_name='transaccion',
            index=models.Index(fields=['estado'], name='operaciones_estado_6779ea_idx'),
        ),
    ]
