# Generated by Django 5.2.5 on 2025-10-15 13:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metodos_pagos', '0001_initial'),
        ('operaciones', '0005_transaccion_ganancia'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaccion',
            name='metodo_pago',
            field=models.ForeignKey(default=1, help_text='Método de pago utilizado en la transacción (ej: efectivo, transferencia).', on_delete=django.db.models.deletion.PROTECT, related_name='transacciones', to='metodos_pagos.metodopago'),
            preserve_default=False,
        ),
    ]
