# Generated by Django 5.2.5 on 2025-10-15 17:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operaciones', '0006_transaccion_metodo_pago'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='transaccion',
            name='fecha_procesado',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='transaccion',
            name='procesado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transacciones_procesadas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='transaccion',
            name='tipo',
            field=models.CharField(choices=[('compra', 'Compra'), ('venta', 'Venta'), ('cambio', 'Cambio')], help_text='Compra o venta.', max_length=10),
        ),
    ]
