# Generated by Django 5.2.5 on 2025-10-26 19:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medio_acreditacion', '0005_tipoentidadfinanciera_comision'),
        ('operaciones', '0007_transaccion_fecha_procesado_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaccion',
            name='medio_acreditacion',
            field=models.ForeignKey(help_text='Medio de acreditacion utilizado para acreditar la transacción (ej: efectivo, transferencia).', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='medio_acreditacion', to='medio_acreditacion.medioacreditacion'),
        ),
    ]
