# Generated by Django 5.2.5 on 2025-10-27 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operaciones', '0008_transaccion_medio_acreditacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaccion',
            name='fecha_retiro',
            field=models.DateTimeField(blank=True, help_text='Fecha y hora del retiro físico', null=True),
        ),
        migrations.AddField(
            model_name='transaccion',
            name='retirado',
            field=models.BooleanField(default=False, help_text='Indica si el cliente ya retiró el dinero físicamente del ATM'),
        ),
    ]
