# Generated by Django 5.2.5 on 2025-10-27 01:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('operaciones', '0009_transaccion_fecha_retiro_transaccion_retirado'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaccion',
            name='fecha_retiro',
        ),
        migrations.RemoveField(
            model_name='transaccion',
            name='retirado',
        ),
    ]
