# Generated by Django 5.2.5 on 2025-10-27 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operaciones', '0010_remove_transaccion_fecha_retiro_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaccion',
            name='monto_recibir',
            field=models.DecimalField(blank=True, decimal_places=8, help_text='Monto exacto que recibirá el cliente (ya con descuento aplicado)', max_digits=20, null=True),
        ),
    ]
