# Generated by Django 5.2.5 on 2025-08-27 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monedas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='moneda',
            name='estado',
            field=models.BooleanField(default=True),
        ),
    ]
