# Generated by Django 5.2.5 on 2025-10-29 21:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('monedas', '0001_initial'),
        ('operaciones', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Localidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('direccion', models.CharField(blank=True, max_length=255)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Localidad',
                'verbose_name_plural': 'Localidades',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Denominacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.DecimalField(decimal_places=2, help_text='Valor de la denominación (ej: 100 para billete de 100)', max_digits=12)),
                ('activo', models.BooleanField(default=True, help_text='Si está activo para uso en TAUSER')),
                ('moneda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='denominaciones', to='monedas.moneda')),
            ],
            options={
                'verbose_name': 'Denominación',
                'verbose_name_plural': 'Denominaciones',
                'ordering': ['-valor'],
                'unique_together': {('moneda', 'valor')},
            },
        ),
        migrations.CreateModel(
            name='MovimientoStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('carga', 'Carga/Aprovisionamiento'), ('retiro', 'Retiro'), ('ajuste', 'Ajuste Manual')], max_length=20)),
                ('cantidad', models.IntegerField(help_text='Cantidad de billetes (positivo para carga, negativo para retiro)')),
                ('stock_anterior', models.IntegerField()),
                ('stock_posterior', models.IntegerField()),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('denominacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movimientos', to='tauser.denominacion')),
                ('transaccion', models.ForeignKey(blank=True, help_text='Transacción asociada si es un retiro de cliente', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimientos_stock', to='operaciones.transaccion')),
            ],
            options={
                'verbose_name': 'Movimiento de Stock',
                'verbose_name_plural': 'Movimientos de Stock',
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='RetiroEfectivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto_total', models.DecimalField(decimal_places=2, max_digits=12)),
                ('monto_entregado', models.DecimalField(decimal_places=2, help_text='Monto real entregado (puede ser menor por falta de denominaciones pequeñas)', max_digits=12)),
                ('diferencia', models.DecimalField(decimal_places=2, default=0, help_text='Diferencia no entregada (resto que no se pudo dar)', max_digits=12)),
                ('metodo_pago', models.CharField(choices=[('efectivo', 'Efectivo'), ('transferencia', 'Transferencia')], default='efectivo', max_length=20)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('localidad', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='retiros', to='tauser.localidad')),
                ('transaccion', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='retiro_efectivo', to='operaciones.transaccion')),
            ],
            options={
                'verbose_name': 'Retiro en Efectivo',
                'verbose_name_plural': 'Retiros en Efectivo',
            },
        ),
        migrations.CreateModel(
            name='DetalleRetiroEfectivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField(help_text='Cantidad de billetes entregados')),
                ('denominacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tauser.denominacion')),
                ('retiro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='tauser.retiroefectivo')),
            ],
            options={
                'verbose_name': 'Detalle de Retiro',
                'verbose_name_plural': 'Detalles de Retiro',
            },
        ),
        migrations.CreateModel(
            name='StockTauser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField(default=0, help_text='Cantidad de billetes disponibles')),
                ('cantidad_minima', models.IntegerField(default=10, help_text='Alerta cuando el stock sea menor a este valor')),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('denominacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock', to='tauser.denominacion')),
                ('localidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stocks', to='tauser.localidad')),
            ],
            options={
                'verbose_name': 'Stock TAUSER',
                'verbose_name_plural': 'Stock TAUSER',
                'unique_together': {('localidad', 'denominacion')},
            },
        ),
    ]
