# Generated by Django 5.2.5 on 2025-10-30 14:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monedas', '0001_initial'),
        ('operaciones', '0002_initial'),
        ('tauser', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReservaTauser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto_total', models.DecimalField(decimal_places=2, max_digits=12)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('expiracion', models.DateTimeField(blank=True, help_text='Fecha/hora en la que expira la reserva (opcional)', null=True)),
                ('activa', models.BooleanField(default=True)),
                ('moneda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='monedas.moneda')),
                ('transaccion', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='reserva_tauser', to='operaciones.transaccion')),
            ],
        ),
        migrations.CreateModel(
            name='DetalleReservaTauser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_reservada', models.IntegerField()),
                ('denominacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tauser.denominacion')),
                ('reserva', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='tauser.reservatauser')),
            ],
        ),
    ]
