# Generated by Django 5.2.6 on 2025-09-26 10:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Entidad",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="Moneda",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("codigo", models.CharField(max_length=10, unique=True)),
                ("nombre", models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="Cliente",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("nombre", models.CharField(blank=True, max_length=100, null=True)),
                ("documento", models.CharField(max_length=20, null=True, unique=True)),
                ("telefono", models.CharField(blank=True, max_length=20, null=True)),
                (
                    "user",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cliente",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Comision",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tipo_transaccion",
                    models.CharField(
                        choices=[
                            ("debito", "Débito"),
                            ("credito", "Crédito"),
                            ("transferencia", "Transferencia"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "porcentaje",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
                ),
                (
                    "monto_fijo",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
                ),
            ],
            options={
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("porcentaje__gte", 0)),
                        name="porcentaje_no_negativo",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("monto_fijo__gte", 0)),
                        name="monto_fijo_no_negativo",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="Cuenta",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nro_cuenta", models.CharField(max_length=30, unique=True)),
                (
                    "saldo",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=15),
                ),
                (
                    "tipo_cuenta",
                    models.CharField(
                        choices=[
                            ("ahorro", "Cuenta de Ahorro"),
                            ("corriente", "Cuenta Corriente"),
                            ("inversion", "Cuenta de Inversión"),
                        ],
                        default="ahorro",
                        max_length=20,
                    ),
                ),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("activa", "Activa"),
                            ("bloqueada", "Bloqueada"),
                            ("cerrada", "Cerrada"),
                        ],
                        default="activa",
                        max_length=20,
                    ),
                ),
                (
                    "cliente",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cuentas",
                        to="transaccion.cliente",
                    ),
                ),
                (
                    "entidad",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="cuentas",
                        to="transaccion.entidad",
                    ),
                ),
                (
                    "moneda",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="cuentas",
                        to="transaccion.moneda",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TasaCambio",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tasa", models.DecimalField(decimal_places=6, max_digits=15)),
                ("fecha", models.DateTimeField(auto_now_add=True)),
                (
                    "moneda_destino",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tasas_destino",
                        to="transaccion.moneda",
                    ),
                ),
                (
                    "moneda_origen",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tasas_origen",
                        to="transaccion.moneda",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Transaccion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("cedula", models.CharField(max_length=15)),
                ("monto", models.DecimalField(decimal_places=8, max_digits=23)),
                ("tipo", models.CharField(max_length=20)),
                ("estado", models.CharField(default="pendiente", max_length=20)),
                ("fecha", models.DateTimeField(auto_now_add=True)),
                (
                    "referencia",
                    models.CharField(blank=True, max_length=50, null=True, unique=True),
                ),
                ("motivo", models.TextField(blank=True, null=True)),
                (
                    "descripcion",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                (
                    "cuenta",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transacciones",
                        to="transaccion.cuenta",
                    ),
                ),
                (
                    "cuenta_destino",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="transferencias_recibidas",
                        to="transaccion.cuenta",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="AuditoriaSaldo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "saldo_anterior",
                    models.DecimalField(decimal_places=2, max_digits=15),
                ),
                ("saldo_nuevo", models.DecimalField(decimal_places=2, max_digits=15)),
                ("fecha", models.DateTimeField(auto_now_add=True)),
                (
                    "cuenta",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="auditoria_saldo",
                        to="transaccion.cuenta",
                    ),
                ),
                (
                    "transaccion",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="transaccion.transaccion",
                    ),
                ),
            ],
        ),
        migrations.AddConstraint(
            model_name="cuenta",
            constraint=models.CheckConstraint(
                condition=models.Q(("saldo__gte", 0)), name="saldo_no_negativo"
            ),
        ),
        migrations.AddConstraint(
            model_name="tasacambio",
            constraint=models.CheckConstraint(
                condition=models.Q(("tasa__gt", 0)), name="tasa_positiva"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="tasacambio",
            unique_together={("moneda_origen", "moneda_destino")},
        ),
        migrations.AddIndex(
            model_name="transaccion",
            index=models.Index(fields=["fecha"], name="transaccion_fecha_013d96_idx"),
        ),
        migrations.AddIndex(
            model_name="transaccion",
            index=models.Index(
                fields=["cuenta", "fecha"], name="transaccion_cuenta__c82829_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="transaccion",
            index=models.Index(fields=["estado"], name="transaccion_estado_c618e1_idx"),
        ),
        migrations.AddIndex(
            model_name="transaccion",
            index=models.Index(fields=["tipo"], name="transaccion_tipo_e0e768_idx"),
        ),
        migrations.AddConstraint(
            model_name="transaccion",
            constraint=models.CheckConstraint(
                condition=models.Q(("monto__gt", 0)), name="monto_positivo"
            ),
        ),
        migrations.AddIndex(
            model_name="auditoriasaldo",
            index=models.Index(
                fields=["cuenta", "fecha"], name="transaccion_cuenta__85c43d_idx"
            ),
        ),
    ]
