# Generated by Django 5.2.6 on 2025-09-21 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('saldo', models.FloatField(default=0.0)),
            ],
        ),
        migrations.CreateModel(
            name='Transaccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('monto', models.FloatField()),
                ('moneda', models.CharField(max_length=3)),
                ('tipo', models.CharField(max_length=10)),
                ('estado', models.CharField(default='pendiente', max_length=20)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('referencia', models.CharField(blank=True, max_length=20, null=True)),
                ('motivo', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
