# Generated by Django 5.2.6 on 2025-09-21 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaccion', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaccion',
            name='moneda',
            field=models.CharField(max_length=10),
        ),
    ]
