# Generated by Django 5.2.6 on 2025-09-25 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaccion', '0004_entidad_moneda_tasacambio_remove_cliente_saldo_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaccion',
            name='cuenta_destino',
        ),
        migrations.RemoveField(
            model_name='transaccion',
            name='usuario_ejecutor',
        ),
        migrations.AddField(
            model_name='transaccion',
            name='cedula',
            field=models.CharField(default=123456, max_length=15),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='transaccion',
            name='estado',
            field=models.CharField(default='pendiente', max_length=20),
        ),
    ]
