# Generated by Django 5.2.6 on 2025-09-25 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaccion', '0005_remove_transaccion_cuenta_destino_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaccion',
            name='tipo',
            field=models.CharField(max_length=20),
        ),
    ]
