# Generated by Django 5.2.6 on 2025-09-25 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaccion', '0006_alter_transaccion_tipo'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaccion',
            name='nro_cuenta',
            field=models.CharField(default=0, max_length=30, unique=True),
            preserve_default=False,
        ),
    ]
