# Generated by Django 5.2.6 on 2025-09-25 15:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transaccion', '0007_transaccion_nro_cuenta'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='user',
        ),
    ]
