# Generated by Django 5.2.6 on 2025-09-25 16:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaccion', '0008_remove_cliente_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaccion',
            name='cuenta_destino',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transferencias_recibidas', to='transaccion.cuenta'),
        ),
    ]
