# Generated by Django 5.2.6 on 2025-09-25 16:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaccion', '0010_remove_transaccion_cuenta_destino_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaccion',
            name='cuenta_destino',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transferencias_recibidas', to='transaccion.cuenta'),
        ),
    ]
