# Generated by Django 5.2.6 on 2025-09-25 17:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transaccion', '0012_transaccion_usuario_ejecutor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaccion',
            name='usuario_ejecutor',
        ),
    ]
