# Generated by Django 5.2.6 on 2025-09-25 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaccion', '0015_alter_transaccion_monto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaccion',
            name='monto',
            field=models.DecimalField(decimal_places=8, max_digits=23),
        ),
    ]
