# Generated by Django 5.2.5 on 2025-08-26 02:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_customuser_roles_alter_customuser_cedula_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='roles',
        ),
    ]
