# Generated by Django 5.2.5 on 2025-08-22 01:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roles_permisos', '0004_remove_rol_usuario'),
        ('usuarios', '0003_rol_descripcion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='rol',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usuarios', to='roles_permisos.rol'),
        ),
        migrations.DeleteModel(
            name='Rol',
        ),
    ]
