# Generated by Django 5.2.5 on 2025-10-07 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_backupcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='mfa_transacciones',
            field=models.BooleanField(default=False),
        ),
    ]
