# Generated by Django 5.2.5 on 2025-08-27 02:03

import django.contrib.auth.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0004_alter_customuser_rol_delete_rol'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='cedula',
            field=models.CharField(error_messages={'blank': 'La cédula es obligatoria.', 'null': 'La cédula no puede ser nula.', 'unique': 'Ya existe un usuario con esta cédula.'}, max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='username',
            field=models.CharField(error_messages={'blank': 'Debes ingresar un nombre de usuario.', 'unique': 'Ya existe un usuario con ese nombre.'}, help_text='Requerido. Hasta 150 caracteres. Letras, números y @/./+/-/_ solamente.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='Nombre de usuario'),
        ),
    ]
