# Generated by Django 5.2.5 on 2025-09-25 20:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '0001_initial'),
        ('monedas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoEntidadFinanciera',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('tipo', models.CharField(choices=[('BANCO', 'Banco'), ('BILLETERA', 'Billetera Digital'), ('COOPERATIVA', 'Cooperativa'), ('FINTECH', 'Fintech'), ('OTRO', 'Otro')], max_length=20)),
                ('estado', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Tipo de Entidad Financiera',
                'verbose_name_plural': 'Tipos de Entidades Financieras',
            },
        ),
        migrations.CreateModel(
            name='MedioAcreditacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_cuenta', models.CharField(help_text='Número de cuenta, teléfono o identificador', max_length=50)),
                ('tipo_cuenta', models.CharField(choices=[('AHORRO', 'Cuenta de Ahorro'), ('CORRIENTE', 'Cuenta Corriente'), ('BILLETERA', 'Billetera Digital'), ('TARJETA_DEBITO', 'Tarjeta de Débito'), ('TARJETA_CREDITO', 'Tarjeta de Crédito'), ('OTRO', 'Otro')], max_length=20)),
                ('titular', models.CharField(help_text='Nombre del titular de la cuenta', max_length=200)),
                ('documento_titular', models.CharField(blank=True, help_text='CI/RUC del titular', max_length=20)),
                ('estado', models.BooleanField(default=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medios_acreditacion', to='clientes.cliente')),
                ('moneda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='monedas.moneda')),
                ('entidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medio_acreditacion.tipoentidadfinanciera')),
            ],
            options={
                'verbose_name': 'Medio de Acreditación',
                'verbose_name_plural': 'Medios de Acreditación',
                'unique_together': {('entidad', 'numero_cuenta')},
            },
        ),
    ]
