# Generated by Django 5.2.5 on 2025-10-29 21:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoEntidadFinanciera',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('tipo', models.CharField(choices=[('BANCO', 'Banco'), ('BILLETERA', 'Billetera Digital'), ('COOPERATIVA', 'Cooperativa'), ('FINTECH', 'Fintech'), ('OTRO', 'Otro')], max_length=20)),
                ('estado', models.BooleanField(default=True)),
                ('comision', models.DecimalField(decimal_places=2, default=0, help_text='Comisión que gana la entidad por transacción', max_digits=8)),
            ],
            options={
                'verbose_name': 'Tipo de Entidad Financiera',
                'verbose_name_plural': 'Tipos de Entidades Financieras',
            },
        ),
        migrations.CreateModel(
            name='MedioAcreditacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.BooleanField(default=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medios_acreditacion', to='clientes.cliente')),
                ('entidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medio_acreditacion.tipoentidadfinanciera')),
            ],
            options={
                'verbose_name': 'Medio de Acreditación',
                'verbose_name_plural': 'Medios de Acreditación',
            },
        ),
        migrations.CreateModel(
            name='CampoEntidadFinanciera',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('etiqueta', models.CharField(max_length=100)),
                ('tipo', models.CharField(choices=[('texto', 'Texto'), ('numero', 'Número'), ('fecha', 'Fecha'), ('email', 'Email')], max_length=20)),
                ('requerido', models.BooleanField(default=True)),
                ('orden', models.PositiveIntegerField(default=0)),
                ('regex_validacion', models.CharField(blank=True, max_length=255)),
                ('mensaje_error', models.CharField(blank=True, max_length=255)),
                ('placeholder', models.CharField(blank=True, max_length=100)),
                ('ayuda', models.CharField(blank=True, max_length=255)),
                ('entidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campos', to='medio_acreditacion.tipoentidadfinanciera')),
            ],
        ),
        migrations.CreateModel(
            name='ValorCampoMedioAcreditacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.CharField(max_length=255)),
                ('campo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medio_acreditacion.campoentidadfinanciera')),
                ('medio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='valores_campos', to='medio_acreditacion.medioacreditacion')),
            ],
        ),
    ]
