# Generated by Django 5.2.5 on 2025-10-29 21:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medio_acreditacion', '0001_initial'),
        ('tauser', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='medioacreditacion',
            name='localidad',
            field=models.ForeignKey(blank=True, help_text='Localidad TAUSER donde se reservan los billetes (solo aplica si entidad es Tauser)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='medios_acreditacion', to='tauser.localidad'),
        ),
    ]
