# Generated by Django 5.2.5 on 2025-10-04 03:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medio_acreditacion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CampoEntidadFinanciera',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('etiqueta', models.CharField(max_length=100)),
                ('tipo', models.CharField(choices=[('texto', 'Texto'), ('numero', 'Número'), ('fecha', 'Fecha'), ('email', 'Email')], max_length=20)),
                ('requerido', models.BooleanField(default=True)),
                ('orden', models.PositiveIntegerField(default=0)),
                ('entidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campos', to='medio_acreditacion.tipoentidadfinanciera')),
            ],
        ),
        migrations.CreateModel(
            name='ValorCampoMedioAcreditacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.CharField(max_length=255)),
                ('campo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medio_acreditacion.campoentidadfinanciera')),
                ('medio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='valores_campos', to='medio_acreditacion.medioacreditacion')),
            ],
        ),
    ]
