# Generated by Django 5.2.5 on 2025-09-22 04:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medio_acreditacion', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='medioacreditacion',
            old_name='activo',
            new_name='estado',
        ),
        migrations.RenameField(
            model_name='tipoentidadfinanciera',
            old_name='activo',
            new_name='estado',
        ),
    ]
