# Generated by Django 5.2.5 on 2025-10-04 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medio_acreditacion', '0002_campoentidadfinanciera_valorcampomedioacreditacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='campoentidadfinanciera',
            name='ayuda',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='campoentidadfinanciera',
            name='mensaje_error',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='campoentidadfinanciera',
            name='placeholder',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='campoentidadfinanciera',
            name='regex_validacion',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
