# Generated by Django 5.2.5 on 2025-09-24 03:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medio_acreditacion', '0002_rename_activo_medioacreditacion_estado_and_more'),
        ('monedas', '0002_moneda_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medioacreditacion',
            name='moneda',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='monedas.moneda'),
        ),
    ]
