# Generated by Django 5.2.5 on 2025-10-05 19:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medio_acreditacion', '0003_campoentidadfinanciera_ayuda_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='medioacreditacion',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='medioacreditacion',
            name='documento_titular',
        ),
        migrations.RemoveField(
            model_name='medioacreditacion',
            name='moneda',
        ),
        migrations.RemoveField(
            model_name='medioacreditacion',
            name='numero_cuenta',
        ),
        migrations.RemoveField(
            model_name='medioacreditacion',
            name='tipo_cuenta',
        ),
        migrations.RemoveField(
            model_name='medioacreditacion',
            name='titular',
        ),
    ]
