# Generated by Django 5.2.5 on 2025-10-11 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medio_acreditacion', '0004_alter_medioacreditacion_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tipoentidadfinanciera',
            name='comision',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Comisión que gana la entidad por transacción', max_digits=8),
        ),
    ]
