# Generated by Django 5.2.5 on 2025-09-25 14:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('monedas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TasaDeCambio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto_compra', models.DecimalField(decimal_places=8, max_digits=23)),
                ('monto_venta', models.DecimalField(decimal_places=8, max_digits=23)),
                ('vigencia', models.DateTimeField()),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('estado', models.BooleanField(default=True)),
                ('moneda_destino', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasas_destino', to='monedas.moneda')),
                ('moneda_origen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasas_origen', to='monedas.moneda')),
            ],
            options={
                'verbose_name': 'Tasa de Cambio',
                'verbose_name_plural': 'Tasas de Cambio',
                'ordering': ['-fecha_actualizacion'],
            },
        ),
    ]
