# Generated by Django 5.2.5 on 2025-08-27 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cotizaciones', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasadecambio',
            name='estado',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='tasadecambio',
            name='monto_compra',
            field=models.DecimalField(decimal_places=8, max_digits=15),
        ),
        migrations.AlterField(
            model_name='tasadecambio',
            name='monto_venta',
            field=models.DecimalField(decimal_places=8, max_digits=15),
        ),
    ]
