# Generated by Django 5.2.5 on 2025-09-27 18:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cotizaciones', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tasadecambio',
            old_name='monto_compra',
            new_name='precio_base',
        ),
        migrations.RemoveField(
            model_name='tasadecambio',
            name='monto_venta',
        ),
    ]
