# Generated by Django 5.2.5 on 2025-10-15 14:21

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cotizaciones', '0002_rename_monto_compra_tasadecambio_precio_base_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasadecambio',
            name='vigencia',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
