# Generated by Django 5.2.5 on 2025-10-16 04:55

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cotizaciones', '0003_alter_tasadecambio_vigencia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasadecambio',
            name='comision_compra',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
        migrations.AlterField(
            model_name='tasadecambio',
            name='comision_venta',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
        migrations.AlterField(
            model_name='tasadecambio',
            name='precio_base',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
    ]
