# Generated by Django 5.2.5 on 2025-08-27 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cotizaciones', '0003_alter_tasadecambio_monto_compra_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasadecambio',
            name='monto_compra',
            field=models.DecimalField(decimal_places=8, max_digits=23),
        ),
        migrations.AlterField(
            model_name='tasadecambio',
            name='monto_venta',
            field=models.DecimalField(decimal_places=8, max_digits=23),
        ),
    ]
