# Generated by Django 5.2.5 on 2025-09-20 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cotizaciones', '0004_alter_tasadecambio_monto_compra_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasadecambio',
            name='comision_compra',
            field=models.DecimalField(decimal_places=8, default=0, max_digits=23),
        ),
        migrations.AddField(
            model_name='tasadecambio',
            name='comision_venta',
            field=models.DecimalField(decimal_places=8, default=0, max_digits=23),
        ),
    ]
