# Generated by Django 5.2.5 on 2025-09-25 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Segmentacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Nombre único de la segmentación', max_length=50, unique=True)),
                ('descripcion', models.TextField(blank=True, help_text='Descripción opcional de la segmentación', null=True)),
                ('descuento', models.DecimalField(decimal_places=2, default=0.0, help_text='Descuento en porcentaje para este tipo de cliente', max_digits=5)),
                ('estado', models.CharField(default='activo', help_text='Estado de la segmentación (activo/inactivo)', max_length=10)),
            ],
        ),
    ]
