# Generated by Django 5.2.5 on 2025-09-04 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cliente_segmentacion', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='segmentacion',
            name='nombre',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
