# Generated by Django 5.2.5 on 2025-09-04 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cliente_segmentacion', '0002_alter_segmentacion_nombre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='segmentacion',
            name='descripcion',
            field=models.TextField(blank=True, help_text='Descripción opcional de la segmentación', null=True),
        ),
        migrations.AlterField(
            model_name='segmentacion',
            name='nombre',
            field=models.CharField(help_text='Nombre único de la segmentación', max_length=50, unique=True),
        ),
    ]
