# Generated by Django 5.2.5 on 2025-09-02 06:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cliente_usuario', '0001_initial'),
        ('clientes', '0005_merge_20250831_1621'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario_Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cliente_usuarios', to='clientes.cliente')),
                ('id_usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usuario_clientes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Usuario Cliente',
                'verbose_name_plural': 'Usuarios Clientes',
                'db_table': 'usuario_cliente',
            },
        ),
        migrations.DeleteModel(
            name='Usuario_Rol_Cliente',
        ),
    ]
