# Generated by Django 5.2.5 on 2025-10-29 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MetodoPago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Nombre único del método de pago (ej: Efectivo, Transferencia)', max_length=100, unique=True)),
                ('descripcion', models.TextField(blank=True, help_text='Descripción detallada del método de pago y sus condiciones', null=True)),
                ('activo', models.BooleanField(default=True, help_text='Indica si el método de pago está disponible para nuevas transacciones')),
                ('comision', models.DecimalField(decimal_places=2, default=0.0, help_text='Porcentaje de comisión aplicado a este método de pago (ej: 2.50 para 2.5%)', max_digits=6)),
            ],
            options={
                'verbose_name': 'Método de Pago',
                'verbose_name_plural': 'Métodos de Pago',
                'ordering': ['nombre'],
            },
        ),
    ]
