# Generated by Django 5.2.5 on 2025-10-14 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metodos_pagos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='metodopago',
            name='comision',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Porcentaje de comisión aplicado a este método de pago (ej: 2.50 para 2.5%)', max_digits=6),
        ),
    ]
