# Generated by Django 5.2.5 on 2025-08-30 21:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('metodos_pagos', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='metodopago',
            options={'verbose_name': 'Método de Pago', 'verbose_name_plural': 'Métodos de Pago'},
        ),
        migrations.RenameField(
            model_name='metodopago',
            old_name='estado',
            new_name='activo',
        ),
    ]
