# Generated by Django 5.2.5 on 2025-09-05 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metodos_pagos', '0002_alter_metodopago_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='metodopago',
            options={'ordering': ['nombre'], 'verbose_name': 'Método de Pago', 'verbose_name_plural': 'Métodos de Pago'},
        ),
        migrations.AlterField(
            model_name='metodopago',
            name='activo',
            field=models.BooleanField(default=False),
        ),
    ]
