# Generated by Django 5.2.5 on 2025-09-15 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metodos_pagos', '0003_alter_metodopago_options_alter_metodopago_activo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='metodopago',
            name='activo',
            field=models.BooleanField(default=True, help_text='Indica si el método de pago está disponible para nuevas transacciones'),
        ),
        migrations.AlterField(
            model_name='metodopago',
            name='descripcion',
            field=models.TextField(blank=True, help_text='Descripción detallada del método de pago y sus condiciones', null=True),
        ),
        migrations.AlterField(
            model_name='metodopago',
            name='nombre',
            field=models.CharField(help_text='Nombre único del método de pago (ej: Efectivo, Transferencia)', max_length=100, unique=True),
        ),
    ]
