# Generated by Django 5.2.5 on 2025-09-25 14:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '0001_initial'),
        ('monedas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LimiteTransaccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('limite_diario', models.DecimalField(decimal_places=2, help_text='Monto máximo permitido por día', max_digits=20)),
                ('limite_mensual', models.DecimalField(decimal_places=2, help_text='Monto máximo permitido por mes', max_digits=20)),
                ('estado', models.CharField(choices=[('activo', 'Activo'), ('inactivo', 'Inactivo')], default='activo', help_text='Estado del límite de transacción', max_length=10)),
                ('cliente', models.ForeignKey(help_text='Cliente al que se le asigna este límite de transacción', on_delete=django.db.models.deletion.CASCADE, related_name='limites_transaccion', to='clientes.cliente')),
                ('moneda', models.ForeignKey(help_text='Moneda para la cual se establece el límite', on_delete=django.db.models.deletion.CASCADE, related_name='limites_transaccion', to='monedas.moneda')),
            ],
            options={
                'verbose_name': 'Límite de Transacción',
                'verbose_name_plural': 'Límites de Transacción',
                'unique_together': {('cliente', 'moneda')},
            },
        ),
    ]
