# Generated by Django 5.2.5 on 2025-10-29 21:13

import django.db.models.deletion
import limite_moneda.models
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('monedas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LimiteTransaccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('limite_diario', models.DecimalField(decimal_places=8, default=Decimal('0'), help_text='Límite máximo por día (en moneda base).', max_digits=20)),
                ('limite_mensual', models.DecimalField(decimal_places=8, default=Decimal('0'), help_text='Límite máximo por mes (en moneda base).', max_digits=20)),
                ('estado', models.CharField(default='activo', max_length=10)),
                ('moneda', models.ForeignKey(blank=True, default=limite_moneda.models.LimiteTransaccion.get_moneda_default, help_text='Moneda base para los límites. Si es None, se buscará la moneda por defecto.', null=True, on_delete=django.db.models.deletion.PROTECT, to='monedas.moneda')),
            ],
            options={
                'verbose_name': 'Límite de Transacción',
                'verbose_name_plural': 'Límites de Transacción',
            },
        ),
    ]
