# Generated by Django 5.2.5 on 2025-09-26 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('limite_moneda', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='limitetransaccion',
            name='limite_diario',
            field=models.DecimalField(decimal_places=8, help_text='Monto máximo permitido por día', max_digits=20),
        ),
        migrations.AlterField(
            model_name='limitetransaccion',
            name='limite_mensual',
            field=models.DecimalField(decimal_places=8, help_text='Monto máximo permitido por mes', max_digits=20),
        ),
    ]
