# Generated by Django 5.2.5 on 2025-09-25 17:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('limite_moneda', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='limitetransaccion',
            unique_together=set(),
        ),
    ]
