# Generated by Django 5.2.5 on 2025-09-30 23:42

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('limite_moneda', '0002_alter_limitetransaccion_limite_diario_and_more'),
        ('monedas', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='limitetransaccion',
            name='cliente',
        ),
        migrations.RemoveField(
            model_name='limitetransaccion',
            name='estado',
        ),
        migrations.AlterField(
            model_name='limitetransaccion',
            name='limite_diario',
            field=models.DecimalField(decimal_places=8, default=Decimal('0'), help_text='Límite máximo por día (en moneda base).', max_digits=20),
        ),
        migrations.AlterField(
            model_name='limitetransaccion',
            name='limite_mensual',
            field=models.DecimalField(decimal_places=8, default=Decimal('0'), help_text='Límite máximo por mes (en moneda base).', max_digits=20),
        ),
        migrations.AlterField(
            model_name='limitetransaccion',
            name='moneda',
            field=models.ForeignKey(blank=True, help_text='Moneda base para los límites. Si es None, se buscará la moneda por defecto.', null=True, on_delete=django.db.models.deletion.PROTECT, to='monedas.moneda'),
        ),
    ]
