# Generated by Django 5.2.5 on 2025-10-01 02:59

import django.db.models.deletion
import limite_moneda.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('limite_moneda', '0003_remove_limitetransaccion_cliente_and_more'),
        ('monedas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='limitetransaccion',
            name='moneda',
            field=models.ForeignKey(blank=True, default=limite_moneda.models.LimiteTransaccion.get_moneda_default, help_text='Moneda base para los límites. Si es None, se buscará la moneda por defecto.', null=True, on_delete=django.db.models.deletion.PROTECT, to='monedas.moneda'),
        ),
    ]
