# Generated by Django 5.2.5 on 2025-10-01 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('limite_moneda', '0004_alter_limitetransaccion_moneda'),
    ]

    operations = [
        migrations.AddField(
            model_name='limitetransaccion',
            name='estado',
            field=models.CharField(default='activo', max_length=10),
        ),
    ]
