# Generated by Django 5.2.5 on 2025-10-21 22:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '0002_initial'),
        ('operaciones', '0007_transaccion_fecha_procesado_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RangoFacturacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('establecimiento', models.CharField(default='001', max_length=3)),
                ('punto_expedicion', models.CharField(max_length=3)),
                ('numero_inicio', models.IntegerField()),
                ('numero_fin', models.IntegerField()),
                ('numero_actual', models.IntegerField()),
                ('equipo', models.CharField(blank=True, max_length=50, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_asignacion', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['establecimiento', 'punto_expedicion', 'numero_inicio'],
                'unique_together': {('establecimiento', 'punto_expedicion', 'numero_inicio')},
            },
        ),
        migrations.CreateModel(
            name='Factura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=10, unique=True)),
                ('cdc', models.CharField(blank=True, max_length=44, null=True, unique=True)),
                ('monto_total', models.DecimalField(decimal_places=2, max_digits=15)),
                ('moneda', models.CharField(max_length=3)),
                ('tipo_cambio', models.DecimalField(decimal_places=4, max_digits=10)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('aprobado', 'Aprobado'), ('rechazado', 'Rechazado'), ('cancelado', 'Cancelado')], default='pendiente', max_length=20)),
                ('estado_sifen', models.CharField(blank=True, max_length=50, null=True)),
                ('descripcion_sifen', models.TextField(blank=True, null=True)),
                ('fecha_emision', models.DateTimeField(auto_now_add=True)),
                ('fecha_aprobacion', models.DateTimeField(blank=True, null=True)),
                ('json_factura', models.JSONField(blank=True, null=True)),
                ('operation_id', models.CharField(blank=True, max_length=50, null=True)),
                ('archivo_kude', models.FileField(blank=True, null=True, upload_to='facturas/kude/')),
                ('archivo_xml', models.FileField(blank=True, null=True, upload_to='facturas/xml/')),
                ('establecimiento', models.CharField(max_length=3)),
                ('punto_expedicion', models.CharField(max_length=3)),
                ('numero_documento', models.CharField(max_length=7)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='clientes.cliente')),
                ('creado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('transaccion', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='operaciones.transaccion')),
                ('rango_utilizado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='facturacion.rangofacturacion')),
            ],
            options={
                'ordering': ['-fecha_emision'],
            },
        ),
    ]
