# Generated by Django 5.2.5 on 2025-10-22 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rangofacturacion',
            name='equipo',
        ),
        migrations.AlterField(
            model_name='rangofacturacion',
            name='punto_expedicion',
            field=models.CharField(default='003', max_length=3),
        ),
    ]
