# Generated by Django 5.2.5 on 2025-10-29 21:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('facturacion', '0001_initial'),
        ('operaciones', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='factura',
            name='creado_por',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='factura',
            name='transaccion',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='operaciones.transaccion'),
        ),
        migrations.AddField(
            model_name='rangofacturacion',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='factura',
            name='rango_utilizado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='facturacion.rangofacturacion'),
        ),
        migrations.AlterUniqueTogether(
            name='rangofacturacion',
            unique_together={('establecimiento', 'punto_expedicion', 'numero_inicio')},
        ),
    ]
