# Generated by Django 5.2.5 on 2025-10-22 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0002_remove_rangofacturacion_equipo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='factura',
            name='moneda',
            field=models.CharField(max_length=10),
        ),
    ]
