# Generated by Django 5.2.5 on 2025-10-22 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0003_alter_factura_moneda'),
    ]

    operations = [
        migrations.AlterField(
            model_name='factura',
            name='numero',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
