# Generated by Django 5.2.5 on 2025-10-29 21:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cotizaciones', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificacionMoneda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activa', models.BooleanField(default=True)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Notificación de Moneda',
                'verbose_name_plural': 'Notificaciones de Monedas',
            },
        ),
        migrations.CreateModel(
            name='AuditoriaTasaCambio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_cambio', models.CharField(choices=[('CREACION', 'Creación'), ('EDICION', 'Edición'), ('DESACTIVACION', 'Desactivación')], max_length=20)),
                ('precio_anterior', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('vigencia_anterior', models.DateField(blank=True, null=True)),
                ('estado_anterior', models.BooleanField(blank=True, null=True)),
                ('precio_nuevo', models.DecimalField(decimal_places=2, max_digits=20)),
                ('vigencia_nueva', models.DateField()),
                ('estado_nuevo', models.BooleanField(default=True)),
                ('fecha_cambio', models.DateTimeField(auto_now_add=True)),
                ('tasa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historial_auditoria', to='cotizaciones.tasadecambio')),
            ],
            options={
                'verbose_name': 'Auditoría de Tasa',
                'verbose_name_plural': 'Auditorías de Tasas',
                'ordering': ['-fecha_cambio'],
            },
        ),
    ]
