# Generated by Django 5.2.5 on 2025-10-07 20:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cotizaciones', '0002_rename_monto_compra_tasadecambio_precio_base_and_more'),
        ('notificaciones', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditoriaTasaCambio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_cambio', models.CharField(choices=[('CREACION', 'Creación'), ('EDICION', 'Edición'), ('DESACTIVACION', 'Desactivación')], max_length=20)),
                ('precio_anterior', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('vigencia_anterior', models.DateField(blank=True, null=True)),
                ('estado_anterior', models.BooleanField(blank=True, null=True)),
                ('precio_nuevo', models.DecimalField(decimal_places=2, max_digits=20)),
                ('vigencia_nueva', models.DateField()),
                ('estado_nuevo', models.BooleanField(default=True)),
                ('fecha_cambio', models.DateTimeField(auto_now_add=True)),
                ('observaciones', models.TextField(blank=True)),
                ('tasa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historial_auditoria', to='cotizaciones.tasadecambio')),
                ('usuario_cambio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cambios_tasa', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Auditoría de Tasa',
                'verbose_name_plural': 'Auditorías de Tasas',
                'ordering': ['-fecha_cambio'],
                'indexes': [models.Index(fields=['-fecha_cambio', 'tasa'], name='notificacio_fecha_c_344159_idx')],
            },
        ),
    ]
