# Generated by Django 5.2.5 on 2025-10-29 21:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('monedas', '0001_initial'),
        ('notificaciones', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='auditoriatasacambio',
            name='usuario_cambio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cambios_tasa', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='notificacionmoneda',
            name='moneda',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notificaciones', to='monedas.moneda'),
        ),
        migrations.AddField(
            model_name='notificacionmoneda',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notificaciones', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='auditoriatasacambio',
            index=models.Index(fields=['-fecha_cambio', 'tasa'], name='notificacio_fecha_c_344159_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='notificacionmoneda',
            unique_together={('user', 'moneda')},
        ),
    ]
