# Generated by Django 5.2.5 on 2025-10-07 20:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notificaciones', '0002_auditoriatasacambio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auditoriatasacambio',
            name='observaciones',
        ),
    ]
