# Generated by Django 5.2.5 on 2025-08-26 02:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('roles_permisos', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rol',
            name='permisos',
        ),
        migrations.DeleteModel(
            name='Permiso',
        ),
        migrations.DeleteModel(
            name='Rol',
        ),
    ]
