# Generated by Django 5.2.5 on 2025-08-22 01:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('roles_permisos', '0003_rol_usuario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rol',
            name='usuario',
        ),
    ]
